[project]
name = "lingchu-bot"
version = "0.1.0"
description = "lingchu-bot"
readme = "README.md"
requires-python = ">=3.12, <4.0"
dependencies = [
    "nonebot2[fastapi,httpx,websockets]==2.4.4",
    "nonebot-adapter-onebot==2.4.6",
    "nonebot-plugin-apscheduler==0.5.0",
    "nonebot-plugin-localstore==0.7.4",
    "nonebot-plugin-sentry==2.0.0",
    "nonebot-plugin-orm[aiosqlite]==0.8.2",
    "nb-cli==1.5.0",
    "aiosqlite==0.21.0",
    "alembic==1.17.2",
    "annotated-doc==0.0.4",
    "annotated-types==0.7.0",
    "anyio==4.11.0",
    "apscheduler==3.11.1",
    "arrow==1.4.0",
    "binaryornot==0.4.4",
    "black==25.11.0",
    "bracex==2.6",
    "bump-my-version==1.2.4",
    "cashews==7.4.3",
    "certifi==2025.11.12",
    "chardet==5.2.0",
    "charset-normalizer==3.4.4",
    "click==8.2.1",
    "colorama==0.4.6 ; sys_platform == 'win32'",
    "cookiecutter==2.6.0",
    "deepmerge==2.0",
    "distlib==0.4.0",
    "exceptiongroup==1.3.1",
    "fastapi==0.122.0",
    "filelock==3.20.0",
    "greenlet==3.2.4",
    "h11==0.16.0",
    "h2==4.3.0",
    "hpack==4.1.0",
    "httpcore==1.0.9",
    "httptools==0.7.1",
    "httpx[http2]==0.28.1",
    "hyperframe==6.1.0",
    "idna==3.11",
    "isort==7.0.0",
    "jinja2==3.1.6",
    "linkify-it-py==2.0.3",
    "loguru==0.7.3",
    "mako==1.3.10",
    "markdown==3.10",
    "markdown-it-py[linkify]==4.0.0",
    "markupsafe==3.0.3",
    "mdit-py-plugins==0.5.0",
    "mdurl==0.1.2",
    "msgpack==1.1.2",
    "multidict==6.7.0",
    "mypy-extensions==1.1.0",
    "nodeenv==1.9.1",
    "nodejs-wheel-binaries==24.11.1",
    "noneprompt==0.1.10",
    "nonestorage==0.1.0",
    "packaging==25.0",
    "pastel==0.2.1",
    "pathspec==0.12.1",
    "platformdirs==4.5.0",
    "poethepoet==0.38.0",
    "prompt-toolkit==3.0.52",
    "propcache==0.4.1",
    "pydantic==2.12.4",
    "pydantic-core==2.41.5",
    "pydantic-settings==2.12.0",
    "pyfiglet==1.0.4",
    "pygments==2.19.2",
    "pygtrie==2.5.0",
    "pymdown-extensions==10.17.1",
    "pyright[nodejs]==1.1.407",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.2.1",
    "python-slugify==8.0.4",
    "pytokens==0.3.0",
    "pyyaml==6.0.3",
    "questionary==2.1.1",
    "requests==2.32.5",
    "rich==14.2.0",
    "rich-click==1.9.4",
    "ruff==0.14.6",
    "sentry-sdk[loguru]==2.45.0",
    "six==1.17.0",
    "sniffio==1.3.1",
    "sqlalchemy[aiosqlite]==2.0.44",
    "starlette==0.50.0",
    "text-unidecode==1.3",
    "textual==6.6.0",
    "tomlkit==0.13.3",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "tzdata==2025.2 ; python_full_version >= '3.9' or sys_platform == 'win32'",
    "tzlocal==5.3.1",
    "uc-micro-py==1.0.3",
    "urllib3==2.5.0",
    "uvicorn[standard]==0.38.0",
    "uvloop==0.22.1 ; platform_python_implementation != 'PyPy' and sys_platform != 'cygwin' and sys_platform != 'win32'",
    "virtualenv==20.35.4",
    "watchfiles==1.1.1",
    "wcmatch==10.1",
    "wcwidth==0.2.14",
    "websockets==15.0.1",
    "win32-setctime==1.2.0 ; sys_platform == 'win32'",
    "yarl==1.22.0",
    "zensical==0.0.9",
]

[project.optional-dependencies]
dev = [
    "pyright[nodejs]",
    "ruff",
    "bump-my-version>=1.2.4",
    "poethepoet>=0.37.0",
    "black>=25.11.0",
    "isort>=7.0.0",
    "zensical>=0.0.9",
]

[tool.nonebot]
plugin_dirs = ["src/plugins"]
builtin_plugins = []

[tool.nonebot.adapters]
nonebot-adapter-onebot = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
]
"@local" = []

[tool.nonebot.plugins]
"@local" = []
nonebot-plugin-apscheduler = ["nonebot_plugin_apscheduler"]
nonebot-plugin-localstore = ["nonebot_plugin_localstore"]
nonebot-plugin-sentry = ["nonebot_plugin_sentry"]
nonebot-plugin-orm = ["nonebot_plugin_orm"]
[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.format]
line-ending = "lf"

[tool.ruff.lint]
# For more rules, see https://docs.astral.sh/ruff/rules/.
select = [
    "F",     # Pyflakes
    "W",     # pycodestyle warnings
    "E",     # pycodestyle errors
    "I",     # isort
    "C90",   # mccabe
    "N",     # pep8-naming
    "PL",    # pylint
    "UP",    # pyupgrade
    "YTT",   # flake8-2020
    "ANN",   # flake8-annotations
    "ASYNC", # flake8-async
    "BLE",   # flake8-blind-except
    "FBT",   # flake8-boolean-trap
    "B",     # flake8-bugbear
    "A",     # flake8-builtins
    "COM",   # flake8-commas
    "C4",    # flake8-comprehensions
    "DTZ",   # flake8-datetimez
    "T10",   # flake8-debugger
    "ICN",   # flake8-import-conventions
    "PIE",   # flake8-pie
    "T20",   # flake8-print
    "PYI",   # flake8-pyi
    "Q",     # flake8-quotes
    "RSE",   # flake8-raise
    "RET",   # flake8-return
    "SIM",   # flake8-simplify
    "SLOT",  # flake8-slots
    "TID",   # flake8-tidy-imports
    "TC",    # flake8-type-checking
    "ARG",   # flake8-unused-arguments
    "PTH",   # flake8-use-pathlib
    # "ERA",   # eradicate
    "FAST", # FastAPI
    "PERF", # Perflint
    "PGH",  # pygrep-hooks
    "FURB", # refurb
    "TRY",  # tryceratops
    "RUF",  # Ruff-specific rules
]
ignore = [
    "E402",  # module-import-not-at-top-of-file  # nonebot2 require() violates this
    "B008",  # function-call-in-default-argument  # nonebot2 Depends() without Annotated violates this
    "UP037", # quoted-annotation
    # "RUF001",  # ambiguous-unicode-character-string
    # "RUF002",  # ambiguous-unicode-character-docstring
    # "RUF003",  # ambiguous-unicode-character-comment
    # "ANN201",  # missing-return-type-undocumented-public-function
    "ANN202",  # missing-return-type-private-function
    "ANN401",  # any-type
    "COM812",  # missing-trailing-comma
    "PLC0415", # import-outside-top-level
    "TID252",  # prefer-absolute-imports
]
allowed-confusables = [
    "，",
    "。",
    "“",
    "”",
    "：",
    "；",
    "？",
    "！",
    "【",
    "】",
    "《",
    "》",
    "…",
    "—",
    "（",
    "）",
    "、",
]

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true

[tool.pyright]
# For Pylance/Pyright configurations, see https://microsoft.github.io/pyright/#/configuration.
pythonVersion = "3.9"
pythonPlatform = "All"
typeCheckingMode = "standard"
